# Generated by Django 5.1.4 on 2024-12-09 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaiBentoCorreto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pbfile',
            old_name='Titulo',
            new_name='title',
        ),
    ]
