# Generated by Django 5.1.4 on 2024-12-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaiBentoCorreto', '0002_rename_titulo_pbfile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbfile',
            name='texto',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
