# Generated by Django 5.1.4 on 2024-12-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaiBentoCorreto', '0003_pbfile_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbfile',
            name='texto',
            field=models.CharField(null=True),
        ),
    ]
